# yaml 配置
version: "3.7"
services:
  mysql8029:
    image: "mysql:8.0.29"
    ports:
      - "33062:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "web_app"
      MYSQL_PASSWORD: "123456"
    restart: always # keep the MySQL server running
    volumes:
      - ./init.sql:/data/application/init.sql
  redis704:
    image: "redis:7.0.4"
    ports:
      - "26379:6379"
  webapp_app:
    build: .
    command: sh -c "./wait-for.sh   mysql8029:3306   redis704:6379 -- ./webapp ./conf/config.ini"
    depends_on:
      - mysql8029
      - redis704
    ports:
      - "8888:8001"