app:
  name: "web_app"
  mode: "dev"
  port: 8000
  version: "1.0.3"

auth:
  jwt_expire: 10080


log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "web_app"
  open_max_conns: 200
  idel_max_conns: 500

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 200

snowflake:
  start_time: "2022-08-08"
  machine_id: 1