app:
  name: "web_app"
  mode: "dev"
  port: 8001
  version: "1.1.5"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "sql_test"
  open_max_conns: 20
  idel_max_conns: 20

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 200